# Predefined calendar kinds with types and URL definitions
kinds:
  simple:
    resource_type: RicCalendar::Calendar
    resource_to_events_attr: events
    event_type: RicCalendar::Event
    event_to_resource_attr: calendar
    event_show_path: ric_calendar.event_path
    event_update_path: ric_calendar.update_schedule_event_path
#  sample_model:
#    resource_type: SampleResource
#    resource_to_events_attr: sample_events
#    event_type: SampleEvents
#    event_to_resource_attr: sample_resource
#    event_show_path: main_app.sample_event_path
#    event_update_path: main_app.update_schedule_sample_event_path 

# Predefined calendar colors
colors:
  yellow:
    primary: "#fff178"
    faded: "#faf3b7"
    text: "black"
  turquoise:
    primary: "#71e8ac"
    faded: "#b5eed1"
    text: "white"
  blue:
    primary: "#a2e1f1"
    faded: "#ceeff7"
    text: "white"
  pink:
    primary: "#ff79a9"
    faded: "#fda8c6"
    text: "white"
  violet:
    primary: "#bdb0ff"
    faded: "#d7d0f6"
    text: "white"
  orange:
    primary: "#f89d7a"
    faded: "#f4baa4"
    text: "white"
  red:
    primary: "#fa7c7c"
    faded: "#f9b8b8"
    text: "white"
  green:
    primary: "#c2f39a"
    faded: "#e0f7cd"
    text: "white"
  grey:
    primary: "#eeeeee"
    faded: "#eeeeee"
    text: "black"