# Use filter column?
use_filter: false

# Use this string to filter slugs valid for this application
#current_app_filter: "key1"

# Use those URLs to form correct links to other applications working on the same slug database
#other_apps_filters:
#  key2: "http://..."
#  key3: "http://..."

# Disable unaccent extension in queries?
disable_unaccent: false