# Define URL template if slug generation enables
url: "/product_category/:product_category_id/products/:id"

# Available currencies
currencies:
  - cs

# Optionaly disable DB function unaccent while search (i.e. PostgreSQL 8.4 does not support this function)
disable_unaccent: false