# Set to true if slugs should be generated. This option depends on RicWebsite engine.
enable_slugs: false

# Define URL template if slug generation enables
url: "/assortment/products/:id"

# Available currencies
currencies:
  - cs

# Optionaly disable DB function unaccent while search (i.e. PostgreSQL 8.4 does not support this function)
disable_unaccent: false