# Model attribute definition (valid only for tableless variant, if save_contact_messages_to_db == false)
attributes:
  -
    name: name
    type: string
  -
    name: email
    type: string
  -
    name: message
    type: string
    required: true