# Settings for client copyright
client:
  name: Klient
  year: 2015
  url: http://www.klient.cz

# Settings for developer copyright
developer:
  name: Clockstar s.r.o.
  url: http://www.clockstar.cz

# Footer menu
menu_items:
  -
    label: headers.ric_portal.public.help
    url: ric_portal.public_help_path
  -
    label: headers.ric_portal.public.contact
    url: ric_portal.public_contact_path