# Active devise features
devise:
  - database_authenticatable
  - recoverable
  - rememberable
  - trackable
  - validatable
#  - registerable
#  - confirmable
#  - lockable
#  - timeoutable
#  - omniauthable

# Avatar crop settings
avatar_crop:
  thumb: "200x200#"
  full: "500x500#"

# Is avatar manually croppable?
avatar_croppable: false