# Available types
#overlap_event_types:
#  - Event1
#  - Event2

# Avalilable reservation states and designated behavior
states:
  - 
    name: yet_closed
    behavior: closed
  - 
    name: open
    behavior: open
  -
    name: soon
    behavior: open
  - 
    name: deadline
    behavior: closed
  - 
    name: already_closed
    behavior: closed
