items:
  -
    label: headers.ric_admin.public.terms
    url: ric_admin.public_terms_path
  -
    label: headers.ric_admin.public.accessibility
    url: ric_admin.public_accessibility_path
  -
    label: headers.ric_admin.public.help
    url: ric_admin.public_help_path
  -
    label: headers.ric_admin.public.contact
    url: ric_admin.public_contact_path