# Which natures can single page obtain
natures:
  home:
    name: "Domovská stránka"
    url: /
  page:
    name: "Běžná stránka"
    url: /website/pages/:page_id

# Which layouts can single page obtain
layouts:
  - default

# Background crop settings
background_crop:
  thumb: "300x300#"
  full: "1920x1920>"