# Which natures can single page obtain
natures:
  home:
    name: "Domovsk치 str치nka"
    url: /
  text:
    name: "Textov치 str치nka"
    url: /public/website/texts/:id
    model: RicWebsite::Text

# Which layouts can single page obtain
layouts:
  - default

# Background crop settings
background_crop:
  thumb: "300x300#"
  full: "1920x1920>"